language: python

python:
  - "2.7"

before_install:
  - sudo add-apt-repository -y -qq ppa:ubuntugis/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libgdal1h gdal-bin libgdal-dev
  - sudo apt-get install -y -qq libblas-dev liblapack-dev

    # numpy (needs fortran to compile)
  - sudo apt-get -y -qq install libblas3gf libc6 libgcc1 libgfortran3 liblapack3gf libstdc++6 build-essential gfortran python-all-dev libatlas-base-dev

    # numpy dependency
  - sudo apt-get -y -qq install python-dev

install:
  - travis_wait "pip install -r requirements.txt"
  - "pip install -r requirements-pysal.txt"
  - "pip install pytest pytest-cov"
  - "pip install coveralls"
  - "pip install -e ."   # install package using setup.py in editable mode

script:
   - py.test --cov geobricks_raster_correlation --cov-report term-missing